Documents/Ruby/rails_projects/cs132alab8-master/config/routes.rb
CloudRegistry::Application.routes.draw do
  get "welcome/register"

  resources :urls

  resources :students

  resources :students do |url|
    resources :urls
  end

  match '/urls' => 'urls#index'
  match '/error' => 'welcome#error'
  match '/welcome/create' =>'welcome#create'
  match '/welcome/:action' =>'welcome#action'
  match '/students' => 'students#view'

  root :to => 'welcome#index'

end

Documents/Ruby/rails_projects/cs132alab8-master/app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :course, :name

  # Write code allows a student to have many urls
  # validate that :name is in the list of allowed students
  # validate that :course is correct 

end

Documents/Ruby/rails_projects/cs132alab8-master/app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :comment, :name, :student_id, :url

  # Write code the shows a url belongs to a student
  # Write code the validates urls have a domain name of herokuapp.com.
end

Documents/Ruby/rails_projects/cs132alab8-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Documents/Ruby/rails_projects/cs132alab8-master/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

Documents/Ruby/rails_projects/cs132alab8-master/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @url = Url.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/new
  # GET /urls/new.json
  def new
    @url = Url.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/1/edit
  def edit
    @url = Url.find(params[:id])
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(params[:url])

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render json: @url, status: :created, location: @url }
      else
        format.html { render action: "new" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /urls/1
  # PUT /urls/1.json
  def update
    @url = Url.find(params[:id])

    respond_to do |format|
      if @url.update_attributes(params[:url])
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
  #  @url = Url.find(params[:id])
  #  @url.destroy
#
#    respond_to do |format|
#      format.html { redirect_to urls_url }
#      format.json { head :no_content }
#  end
  end
end

Documents/Ruby/rails_projects/cs132alab8-master/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def register
  end

  # GET /urls
  # GET /urls.json
  def index

    # We will be creating a new student object to use with Register URL form
    @student = Student.new 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  def create
    # Create a student
    # You can see the Students table id db/migrate
    @student = Student.new({:name =>params[:student][:name],:course => params[:student][:course]})

    respond_to do |format|
      # add the URL to the student
      # Ruby will give the URL the correct student_id
      if @student.save and @student.urls.create!({:name => '',:url => params[:url]})
        format.html { redirect_to  '/urls', notice: 'Url was successfully created.' }
        format.json { render json: @url, status: :created, location: @url }
      else
        # If the form doesn't validate we'll just redirect.
        # We have to create a route in config/routes.rb for this to work
        format.html { redirect_to  '/error'}
      end
    end
  end
end

Documents/Ruby/rails_projects/cs132alab8-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Documents/Ruby/rails_projects/cs132alab8-master/app/helpers/students_helper.rb
module StudentsHelper
end

Documents/Ruby/rails_projects/cs132alab8-master/app/helpers/urls_helper.rb
module UrlsHelper
end

Documents/Ruby/rails_projects/cs132alab8-master/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Documents/Ruby/rails_projects/cs132alab8-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "CS 132A Heroku App" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
  <style>body {padding-top:0px}.dark-background {background-color:#333}</style>
</head>
<body>
  <div class="contain-to-grid">
    <nav class="top-bar">
      <ul>
        <li class="name">
          <a href="/">Register your Heroku URL</a>
        </li>
        <li><a href="/urls">Class Links</a></li>
        <li class="toggle-topbar"><a href="#"></a></li
      </ul>
      <section>
      <ul class="right">
        <li><a href="/welcome/assignment" style="color:lime">Read the Assignment!</a>
        <li><a href="http://insight.ccsf.edu">Insight</a>
        <li><a href="http://webaccess.mrooms.net">WebAccess</a>
        <li><a href="http://hackingthevalley.com">HTV</a>
      </ul>
      </section>
    </nav>
  </div>


  <div class="row">
      <div class="twelve columns">
  <%= yield %>
      </div>
  </div>
</body>
</html>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/layouts/orig.application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudRegistry</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "html5", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>#globalWrapper {width:100%}#top-header {height:40px;padding:12px 0;text-align:center;font-size:13px; background-color:black;color:#eee}</style>
</head>
<body>
  <aside id="top-header">
links go here.
  </aside>
  <section id="globalWrapper">
    <article id="main">

<%= yield %>

    </article>
  </section>
  <footer id="footer">

  </footer>
</body>
</html>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Course</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.course %></td>
    <td><% student.urls.each do |u| %>
          <a href="<%= u.url %>"><%= u.url %></a>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Course:</b>
  <%= @student.course %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/urls/index.html.erb
<div class="row">
<div class="twelve columns">
  <h3>Currently Registered</h3>
<table>
  <tr>
    <th>Course</th>
    <th>Student</th>
    <th>Url</th>
  </tr>

<% @students.each do |s| %>
  <% s.urls.each do |u| %>
    <tr>
      <td><%= s.course %></td>
      <td><%= s.name %></td>
      <td><a href="<%= u.url %>" title="<%= s.name %>"><%= u.url %></a></td>
    </tr>
  <% end %>
<% end %>
</table>
</div>
<%= link_to 'Enter another URL', '/',:html => {:class => 'nav'} %>
</div>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @url.name %>
</p>

<p>
  <b>Url:</b>
  <%= @url.url %>
</p>

<p>
  <b>Comment:</b>
  <%= @url.comment %>
</p>

<p>
  <b>Student:</b>
  <%= @url.student_id %>
</p>


<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/welcome/assignment.html.erb
<!doctype html>
<head>
<meta charset="utf-8">
<title>
Ruby Programming: Week 16 Lab 8 -- Rails ActiveRecord Associations and Routes
</title>
<link rel="stylesheet" type="text/css" href="foundation.min.css"> <link rel="stylesheet" type="text/css" href="lyx.css"> <link rel="stylesheet" type="text/css" href="counter.css">
<style>

/* Itemizes H2, h3, and H4 elements */
div#globalWrapper {
  counter-reset: header1_counter 0;
  counter-reset: header2_counter 0;
  counter-reset: header3_counter 0;
  counter-reset: header4_counter 0;
}

div#globalWrapper h2 {
  counter-increment: header2_counter;
  counter-reset: header3_counter 0;
}

div#globalWrapper h3 {
  counter-increment: header3_counter;
  counter-reset: header4_counter 0;
}

div#globalWrapper h4 {
  counter-increment: header4_counter;
}

div#globalWrapper  h2:before {
  counter-reset: header3_counter 0;
  content: counter(header2_counter, decimal) ' ';
}

div#globalWrapper  h3:before {
    content: counter(header2_counter, decimal) '.' counter(header3_counter, decimal) ' ';
    counter-reset: header4_counter 0;
    font-size: 80%;
}

div#globalWrapper  h4:before {
    content: counter(header2_counter, decimal) '.' counter(header3_counter, decimal) '.' counter(header4_counter, decimal) ' ';
    font-size: 80%;
}
#globalWrapper ol,#globalWrapper  ul {
  list-style-position:inside;
}

h1 ,h2,h3,h4,h5,code, h1 a,h2 a,h3 a,h4 a,h5 a {font-weight: 400;margin:1em 0}
body,p,div,th,td,li,dd,dt,input, blockquote,textarea,pre,tt,strike,del {color:black;font-size:16px;line-height:1.5}

pre {white-space:pre-wrap;word-wrap:break-word; margin:1em 0}
</style>
</head>
<blockquote>


</blockquote>
<div class="row">
<div class="twelve columns">
<section id="globalWrapper">
<h1 id="active-record-associations-has_many-and-belongs_to">Active Record Associations <code>has_many</code> and <code>belongs_to</code></h1>
<blockquote>
<h2>Overview</h2>
<h5>This is the final assignment for the semester. It's been a long haul, and I'm impressed that so many of you guys have hung in for the duration. I applaud all of you for hanging in. <strong>Kudos, to all!</strong></h5>
<hr>

<p>In Week 16 you will work with an existing Rails application and modify it to display the collected links to the Heroku Rails apps created by my CSM and CCSF Spring semester Ruby students.</p>
<h3>Reading and Online Resources</h3>
<ul>
<li><em>Beginning Ruby: Chapter 13 – Ruby on Rails: Ruby's Killer App#Models and Relationships</em>[p. 277]</li>
<li>Active Record associations: <a href="http://guides.rubyonrails.org/association_basics.html">A Guide to Active Record Associations</a></li>
<li>Active Record Query Interface: <a href="http://guides.rubyonrails.org/active_record_querying.html">http://guides.rubyonrails.org/active_record_querying.html</a></li>

<h3>Example Rails applications</li>
<li><a href="http://polar-journey-7101.herokuapp.com">http://polar-journey-7101.herokuapp.com</a> (Rails 2.2.2)</li>
<li><a href="http://hackingthevalley.com">http://hackingthevalley.com</a></li>
</ul>
</blockquote>
</section>
<div id="globalWrapper">
<h2 id="installing-the-ruby-course-rails-app">Installing the ruby-course Rails App</h2>
<p>This is the final lab assignment for this course.</p>
<p>In this lab you will modify an existing application named <code>ruby-course</code> to add a feature the the form page. This Rails app is available from my Github account: <a href="https://github.com/douglasputnam/cs132alab8.git">https://github.com/douglasputnam/cs132alab8.git</a></p>
<h3 id="follow-these-steps">FOLLOW THESE STEPS</h3>
<ol style="list-style-type: decimal">
<li><p>Do a <code>git add .; git commit</code> of your current Heroku app. We will not use the app we created in labs 7a and 7b is app for this assignment.</p></li>
<li><p>Do a <code>git clone</code> of ruby-course:</p>
<pre class="LyX-Code"><code>git clone https://github.com/douglasputnam/cs132alab8.git</code></pre></li>
<li><p>Log in to your Heroku account and remove your Heroku app — yes, the one you worked so hard on. After the course you can restore your work from the git archive you have already created.</p></li>
<li><p>Recreate your Heroku app. You can use the same name (recommended) or you can create an entirely new app with a different name.</p></li>
<li><p>On your computer, go to the <code>ruby-course</code> folder (the one you cloned from Github). Set up git and heroku again to work with this new code.</p></li>
<li><p>In the <code>ruby-course</code> folder do:</p>
<pre class="LyX-Code"><code>bundle install</code></pre></li>
<li><p>Then do:</p>
<pre class="LyX-Code"><code>git add .
git commit -m &#39;initial commit&#39;</code></pre></li>
<li><p>Do a: <code>git push heroku master</code></p></li>
<li><p>On the command, create the database tables on Heroku: <code>heroku run rake db:migrate</code></p></li>
<li><p>Then go the your Heroku app's URL to see if your site is working. If it is, hooray! If it's not, check that you went through the previous steps correctly. If you are still having problems, post your questions on the forum.</p></li>
</ol>
<h3 id="alternate-plan">Alternate Plan</h3>
<p>Though it's easier to use the <code>ruby-course</code> app as it stands, you may want to integrate it into your current Heroku app. This will likely be extra work, but you can do it by creating the necessarey Classes and Models.</p>
<h2 id="lab-8-todo">Lab 8 TODO</h2>

<p>The home page (<code>welcome#index</code>) currently displays only the registration form. Your job is to:</p>
<ol style="list-style-type: decimal">
    <li>Write code that displays all of the collected links on the <code>welcome#index</code> page.</li>
    <li>Write code that displays all of the collected urls on the <code>urls#index</code> page.</li>
<li>Creates HREF links to the URL.</li>
<li>Give your script the same functionality as <a href="http://polar-journey-7101.herokuapp.com">this example</a>.</li>
</ol>

<h3 id="edit-these-files-at-least">Edit these files (at least):</h3>
<ol style="list-style-type: decimal">
<li><code>app/controllers/welcome_controller.rb</code>: Write code that will read the database for the links to all registered student Heroku sites.</li>
<li><code>app/views/welcome/index.html.erb</code>: Write code that displays the data prepared by the <code>welcome_controller.rb</code>.</li>
<li><code>app/models/student.rb</code>: A Student can have many URLs; validates that the student's name is in the list of registered students.</li>
<li><code>app/models/url.rb</code>: URLs belong to a student; validates that the URL is a <strong>herokuapp.com</strong> URL.</li>
<li><code>app/views/urls/index.html.erb</code>: Display a confirmation message when a new URL has been registered; display the collected URLs </strong> URL.</li>
</ol>
<h3 id="running-migrations">Running Migrations</h3>
<p>After git-cloning the ruby-course app, you will have to run <em>rake db:migrate</em> to create the database tables for Students and Urls.</p>
<pre class="LyX-Code"><code>rake db:migrate</code></pre>
<h3 id="routes">Routes</h3>
<p>Routes are one of the most confusing aspects of Rails. Look at the <code>config/routes.rb</code> file to see how the routes work in this application. To see all of the routes in the application, you can run:</p>
<pre class="LyX-Code"><code>rake routes</code></pre>
<h3 id="validation">Validation</h3>
<p>Modify the Student and Url model to validate Students and Urls. Students can <code>:have_many</code> Urls; Urls <code>:belongs_to</code> a Student.</p>

<h4>Students</h4>
<p>For this assignment, the only allowed user names are in the list below.</p>
<ol style="list-style-type: decimal">
<li><p>Modify the default <code>student.rb</code> file to allow only students from this list to add URLs to the list.</p>
<pre><code>dputnam,adesilv1,ryaryy,rgorreap,ubenesch,zng1,jswanner,npachec2,avalenc7,bmckeand,mpernabe,dott,bernst,tcoffey1,gpaz,ywun,mweaver3,jsteele,pkassian,psakhark,jsotobus,bkrantzi,crosales,jmencha1,asushon,kchan131,mhankins,jmonto10,jreed13,ikim5,jpayne,ktieu,kposey1,dlouie11,zbazarra,tho36,tparas,amanayan,jgarc166</code></pre></li>
</ol>


<h4>Urls</h4>
<ol><li><p>Modify the default <code>url.rb</code> file so that only URLs the end with <code>herokuapp.com</code> will be accepted into the database.</p></li><li>Urls must belong to a Student.</li>
</ol>

<p>Feel free modify these files in any way so long as your mods meet the required specs for this assignment.</p>

<h2 id="pagination-optional">Pagination (optional)</h2>
<p>Eventually you will have more URLs than you want to show on a single page. At that point you will have to think about pagination. Install the <code>will_paginate</code> gem (it worked in 2012). Read the documention to see how to use this plugin.</p>
<h2 id="submit">SUBMIT</h2>
<ol style="list-style-type: decimal">
    <li><strong>VERY IMPORTANT:</strong> Create a Ruby CGI filed named <strong>lab8.cgi</strong> and upload it to your Hills <code>cs132a</code> directory. The script should display a link to your Heroku app. If you do not post a link to your Heroku app, I will not be able to grade your assignment and you will not get full credit. <em>I will not assume that you are using the same Heroku app you used in labs 7a and 7b</em>.
    <li>Deploy your completed app to Heroku.</li>
    <li>Using the Week 16: Assignment 8 Upload link, submit your entire app as a zip file named <strong>lab8.zip</strong>.</li>
</ol>
<h2 id="communication">Communication</h2>
<p>This assignment is challenging. If you find yourself hitting a wall, ask your questions on the forums quickly so you can get answers and get back on track. And, if you see something in the assignment that doesn't work the way it should, please contact me so that I can fix it.</p>

<p>I'm looking forward to see your improvements to the ruby-course app. :)</p>

<p>Have fun.</p>
<hr />
</div>
</div>
</div>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/welcome/error.html.erb
<div class="row">
  <div class="four columns centered">
<div class="row">
  <div class="twelve columns centered panel">
<h2>Error</h2>
<p>To enter your URL into this form, you must 
<ul class="circle"><li>Be a member of the CCSF or CSM Ruby programming class</li> <li>Be submitting a Heroku URL</li></ul></p>
</div>
</div>
<div class="row">
  <div class="twelve columns centered ">

<h3>Register for Ruby</h3>
<h5>CSM</h5>
<ul class='circle'>
<li><a href="http://www.collegeofsanmateo.edu">College of San Mateo</a></li>
<li><a href="http://www.ccsf.edu">City College of San Francisco</a></li>
</ul>
</div>
</div>
</div>
</div>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/welcome/index.html.erb
<div class="row">
  <br>
</div>
<div style="background-color:transparent">
  <div class="row">
    <div class="twelve columns left" style="padding-top:2em;padding-bottom:2em">
      <h1 id='site-title'>Ruby Programming <small>Heroku Registry</small></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="four columns">
    <div class="panel radius" style="background-color:#ff8">
      <h4>Link to Your App</h4>
      <p>Use this form to enter the URL for your Ruby Programming Heroku Rails Application. This form is
      collecting URLs from both of my Ruby courses at <a href="http://hackingthevalley.com/ccsf/ruby">City College of San Francisco</a>. <%# <%#and <a href="http://hackingthevalley.com/csm/ruby">College of San Mateo%>.</a> %></p>
        <p>Enter your USERID and your HEROKU app.</p>
      <p>Read the <a href="/welcome/assignment">assignment</a>.</p>
      </div>
    </div>
    <div class="eight columns" style="background-color:#f0f0f0;">
      <h3>Register your Heroku URL</h3>
      <%= form_for @student, :url => {:action => 'create'} do |f| %>
      <p>
        <%= f.label :COURSE %>
      </p>
      <p>
        <%= f.select :course, options_for_select(['Choose your course',['CS 132A','cs132a'],['CIS 113','cis113']]) %>
      </p>
      <p>
        <%= f.label :USERID %>
      </p>
      <p>
        <%= f.text_field :name, :placeholder =>'Your USERID' %>
      </p>
      <p>
        <%= f.label :URL %>
      </p>
      <p>
        <input type="url" name="url" placeholder="Heroku URL"/>
      </p>
      <input type="submit" class="round button" value="Register" />
      <% end %>
    </div>
  </div>
<div style="margin:1em 0; height:40px;clear:both;"><br></div>
<div class="row">
  <div class="twelve columns panel callout">
    <h2>Your output will go here...</h2>
    <h5>
        <p>
      When you are finished this assignment, your app will display links to class Heroku web sites here. 
      Go to the <a href="http://polar-journey-7101.herokuapp.com">example</a> to see how your
      page should behave. 
      </p>
      <p>Register your own site into your Registry.</p>
    </h5>
  </div>
</div>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/welcome/register.html.erb
<h1>Welcome#register</h1>
<p>Find me in app/views/welcome/register.html.erb</p>

Documents/Ruby/rails_projects/cs132alab8-master/app/views/welcome/success.html.erb
<H1>Success</h1>

<a href="/">Try again</a>